"""empty message

Revision ID: 2c3dd6ea419
Revises: None
Create Date: 2015-04-23 13:54:02.687463

"""

# revision identifiers, used by Alembic.
revision = '2c3dd6ea419'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('first_name', sa.String(length=100), server_default='', nullable=False))
    op.add_column('user', sa.Column('is_active', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(length=100), server_default='', nullable=False))
    op.add_column('user', sa.Column('reset_password_token', sa.String(length=100), server_default='', nullable=False))
    op.drop_column('user', 'active')
    op.create_unique_constraint(None, 'user', ['email'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user')
    op.add_column('user', sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('user', 'reset_password_token')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'email')
    op.drop_column('user', 'confirmed_at')
    op.drop_constraint(None, 'decoding')
    ### end Alembic commands ###
