"""empty message

Revision ID: 37527466ef9e
Revises: 4248e6fe3b9e
Create Date: 2015-05-04 17:43:51.795464

"""

# revision identifiers, used by Alembic.
revision = '37527466ef9e'
down_revision = '4248e6fe3b9e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_analysis', sa.Column('private', sa.Boolean(), nullable=True))
    # op.drop_constraint(u'url', 'decoding')
    # op.drop_constraint(u'name', 'gene')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'name', 'gene', ['name'])
    op.create_unique_constraint(u'url', 'decoding', ['url'])
    op.drop_column('custom_analysis', 'private')
    ### end Alembic commands ###
