"""empty message

Revision ID: 3b19daeaf23c
Revises: None
Create Date: 2014-08-20 12:14:31.454311

"""

# revision identifiers, used by Alembic.
revision = '3b19daeaf23c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uuid', sa.String(length=32), nullable=True),
    sa.Column('ip', sa.String(length=15), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('inclusion',
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('study_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], [u'analysis.id'], ),
    sa.ForeignKeyConstraint(['study_id'], [u'study.pmid'], ),
    sa.PrimaryKeyConstraint('analysis_id', 'study_id')
    )
    op.add_column(u'feature', sa.Column('display', sa.Boolean(), nullable=True))
    op.add_column(u'image', sa.Column('analysis_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'image', 'analysis_id')
    op.drop_column(u'feature', 'display')
    op.drop_table('inclusion')
    op.drop_table('analysis')
    ### end Alembic commands ###
