"""empty message

Revision ID: 4248e6fe3b9e
Revises: 2c3dd6ea419
Create Date: 2015-04-28 13:18:49.518820

"""

# revision identifiers, used by Alembic.
revision = '4248e6fe3b9e'
down_revision = '2c3dd6ea419'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_analysis', sa.Column('last_run_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_analysis', 'last_run_at')
    ### end Alembic commands ###
